
DROP FUNCTION obtener_delegacion_por_ca;

BEGIN
   FOR p IN (SELECT object_name 
             FROM user_objects 
             WHERE object_type = 'PROCEDURE') LOOP
      EXECUTE IMMEDIATE 'DROP PROCEDURE ' || p.object_name;
   END LOOP;
END;
/


BEGIN
   FOR t IN (SELECT trigger_name FROM user_triggers) LOOP
      EXECUTE IMMEDIATE 'DROP TRIGGER ' || t.trigger_name;
   END LOOP;
END;
/


DROP VIEW Empleado CASCADE CONSTRAINTS;
DROP VIEW Sucursal CASCADE CONSTRAINTS;
DROP VIEW Cliente CASCADE CONSTRAINTS;
DROP VIEW Vino CASCADE CONSTRAINTS;
DROP VIEW SucursalVendeVino CASCADE CONSTRAINTS;
DROP VIEW ClienteSolicitaSuministro CASCADE CONSTRAINTS;    


--luna1
DROP TABLE Empleado1 CASCADE CONSTRAINTS;
DROP TABLE Sucursal1 CASCADE CONSTRAINTS;
DROP TABLE Cliente1 CASCADE CONSTRAINTS;
DROP TABLE Vino1 CASCADE CONSTRAINTS;
DROP TABLE Productor CASCADE CONSTRAINTS;
DROP TABLE SucursalVendeVino1 CASCADE CONSTRAINTS;
DROP TABLE ClienteSolicitaSuministro1 CASCADE CONSTRAINTS;
DROP TABLE SucursalPideSuministro CASCADE CONSTRAINTS;  


DROP TABLE Empleado2 CASCADE CONSTRAINTS;
DROP TABLE Sucursal2 CASCADE CONSTRAINTS;
DROP TABLE Cliente2 CASCADE CONSTRAINTS;
DROP TABLE Vino2 CASCADE CONSTRAINTS;
DROP TABLE Productor CASCADE CONSTRAINTS;
DROP TABLE SucursalVendeVino2 CASCADE CONSTRAINTS;
DROP TABLE ClienteSolicitaSuministro2 CASCADE CONSTRAINTS;
DROP TABLE SucursalPideSuministro CASCADE CONSTRAINTS;  

DROP TABLE Empleado3 CASCADE CONSTRAINTS;
DROP TABLE Sucursal3 CASCADE CONSTRAINTS;
DROP TABLE Cliente3 CASCADE CONSTRAINTS;
DROP TABLE Vino3 CASCADE CONSTRAINTS;
DROP TABLE Productor CASCADE CONSTRAINTS;
DROP TABLE SucursalVendeVino3 CASCADE CONSTRAINTS;
DROP TABLE ClienteSolicitaSuministro3 CASCADE CONSTRAINTS;
DROP TABLE SucursalPideSuministro CASCADE CONSTRAINTS;  


DROP TABLE Empleado4 CASCADE CONSTRAINTS;
DROP TABLE Sucursal4 CASCADE CONSTRAINTS;
DROP TABLE Cliente4 CASCADE CONSTRAINTS;
DROP TABLE Vino4 CASCADE CONSTRAINTS;
DROP TABLE Productor CASCADE CONSTRAINTS;
DROP TABLE SucursalVendeVino4 CASCADE CONSTRAINTS;
DROP TABLE ClienteSolicitaSuministro4 CASCADE CONSTRAINTS;
DROP TABLE SucursalPideSuministro CASCADE CONSTRAINTS;  
